Output non-formula output (errors) if the user passes `--verbose`
- Otherwise, in normal output when in use in a shell script to pass the
  output to `brew build-bottle-pr`, this happens:
  ```
Warning: git-extras: Skipping because a PR is open
Warning: git: Skipping because a PR is open
Warning: mmark: Skipping because a PR is open
Error: No available formula with the name "git-extras:"
Error: No available formula with the name "build"
Error: No available formula with the name "a"
Error: No available formula with the name "bottle"
Error: No available formula with the name "for"
Error: No available formula with the name "linuxbrew"
Error: bad URI(is not URI?): (https://github.com/Homebrew/linuxbrew-core/pull/...)
  ```
- This will cause output to be silenced in normal use, but given the
  same HEAD merge commit, re-running manually with `--verbose` will tell
  you what was wrong.