find-formulae-to-bottle: require "formula"
With recent changes in `brew`, this is necessary to fix:
```
Error: undefined method `[]' for Formula:Class
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/find-formulae-to-bottle.rb:82:in `block in find_formulae_to_bottle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/find-formulae-to-bottle.rb:80:in `reject!'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-linux-dev/cmd/find-formulae-to-bottle.rb:80:in `find_formulae_to_bottle'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```